workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Set permissions
        script: chmod +x gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
